# Generated by Django 3.2.25 on 2026-01-25 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oj_problem', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(max_length=102400, verbose_name='source code')),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('python3', 'Python 3')], max_length=10, verbose_name='language')),
                ('status', models.IntegerField(choices=[(-4, 'pending'), (-3, 'judging'), (-2, 'compile error'), (-1, 'wrong answer'), (0, 'accepted'), (1, 'time limit exceeded'), (2, 'memory limit exceeded'), (3, 'runtime error'), (4, 'system error')], default=-4, verbose_name='status')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('execute_time', models.IntegerField(default=0, verbose_name='execute time')),
                ('execute_memory', models.IntegerField(default=0, verbose_name='execute memory')),
                ('detail', models.JSONField(default=list, verbose_name='execute detail')),
                ('log', models.TextField(blank=True, default='', max_length=400, verbose_name='execute log')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('_is_hidden', models.BooleanField(default=False, verbose_name='hidden')),
                ('allow_download', models.BooleanField(default=True, verbose_name='allow download')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='oj_problem.problem', verbose_name='problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
            },
        ),
    ]
