# Generated by Django 3.2.25 on 2026-01-25 12:19

from django.db import migrations, models
import django.db.models.deletion
import oj_problem.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('background', models.TextField(blank=True, default='', verbose_name='background')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('input_format', models.TextField(blank=True, default='', verbose_name='input format')),
                ('output_format', models.TextField(blank=True, default='', verbose_name='output format')),
                ('sample_1', models.JSONField(default=oj_problem.models.get_default_sample, verbose_name='sample 1')),
                ('sample_2', models.JSONField(default=oj_problem.models.get_default_sample, verbose_name='sample 2')),
                ('sample_3', models.JSONField(default=oj_problem.models.get_default_sample, verbose_name='sample 3')),
                ('hint', models.TextField(blank=True, default='', verbose_name='hint')),
                ('difficulty', models.IntegerField(default=0, help_text='level: 0 to 7, 0 for unset', verbose_name='difficulty')),
                ('time_limit', models.IntegerField(default=1000, verbose_name='time limit (ms)')),
                ('memory_limit', models.IntegerField(default=128, verbose_name='memory limit (MB)')),
                ('_is_hidden', models.BooleanField(default=False, verbose_name='hide')),
                ('_hide_submissions', models.BooleanField(default=False, verbose_name='hide submissions')),
                ('_hide_discussions', models.BooleanField(default=False, verbose_name='hide discussions')),
                ('_allow_submit', models.BooleanField(default=True, verbose_name='allow submit')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('submission_count', models.IntegerField(default=0, verbose_name='submission count')),
                ('accepted_count', models.IntegerField(default=0, verbose_name='solved count')),
                ('files', models.JSONField(default=list, verbose_name='problem files')),
            ],
            options={
                'verbose_name': 'problem',
                'verbose_name_plural': 'problems',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='tag name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.UUIDField(default=uuid.uuid1, verbose_name='test case id')),
                ('test_case_config', models.JSONField(blank=True, default=list, verbose_name='test case config')),
                ('use_spj', models.BooleanField(default=False, verbose_name='spj')),
                ('spj_id', models.UUIDField(default=uuid.uuid1, verbose_name='spj id')),
                ('spj_mode', models.CharField(blank=True, choices=[('NULL', 'NULL'), ('traditional', 'Traditional (CXX)'), ('simple', 'Simple (Python3)')], default='NULL', max_length=20, verbose_name='spj mode')),
                ('spj_source', models.TextField(blank=True, default='', verbose_name='spj_source')),
                ('subcheck_config', models.JSONField(blank=True, default=list, verbose_name='subcheck config')),
                ('use_subcheck', models.BooleanField(default=False, verbose_name='subcheck')),
                ('allow_download', models.BooleanField(default=False, verbose_name='allow download case data')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='oj_problem.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'testcase',
                'verbose_name_plural': 'testcases',
            },
        ),
        migrations.CreateModel(
            name='ProblemSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_solve', to='oj_problem.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'problem solve data',
                'verbose_name_plural': 'problem solve data',
            },
        ),
    ]
