# Generated by Django 3.2.25 on 2026-01-25 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oj_problem', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='hide')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='hide')),
                ('is_disbanded', models.BooleanField(default=False, help_text='解散后的班级不可见', verbose_name='disbanded')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10, verbose_name='role')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='joined at')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='oj_class.class', verbose_name='class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'class student',
                'verbose_name_plural': 'class students',
                'unique_together': {('class_obj', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ClassProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('input_format', models.TextField(blank=True, verbose_name='input format')),
                ('output_format', models.TextField(blank=True, verbose_name='output format')),
                ('hint', models.TextField(blank=True, verbose_name='hint')),
                ('time_limit', models.IntegerField(default=1000, verbose_name='time limit')),
                ('memory_limit', models.IntegerField(default=128, verbose_name='memory limit')),
                ('difficulty', models.CharField(blank=True, max_length=20, verbose_name='difficulty')),
                ('test_case_config', models.JSONField(default=list, verbose_name='test case config')),
                ('samples', models.JSONField(default=list, verbose_name='samples')),
                ('is_reference', models.BooleanField(default=False, verbose_name='is reference')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='oj_class.class', verbose_name='class')),
                ('reference_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_references', to='oj_problem.problem', verbose_name='reference problem')),
            ],
            options={
                'verbose_name': 'class problem',
                'verbose_name_plural': 'class problems',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='joined_classes', through='oj_class.ClassStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='teacher'),
        ),
        migrations.CreateModel(
            name='AssignmentProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj_class.assignment', verbose_name='assignment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj_class.classproblem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'assignment problem',
                'verbose_name_plural': 'assignment problems',
                'ordering': ['order'],
                'unique_together': {('assignment', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='oj_class.class', verbose_name='class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='problems',
            field=models.ManyToManyField(related_name='assignments', through='oj_class.AssignmentProblem', to='oj_class.ClassProblem'),
        ),
    ]
