# Generated by Django 3.2.25 on 2026-02-22 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oj_problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('cover', models.FileField(blank=True, null=True, upload_to='book_covers/', verbose_name='cover')),
                ('difficulty', models.CharField(choices=[('beginner', '入门'), ('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='beginner', max_length=20, verbose_name='difficulty')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('reader_count', models.IntegerField(default=0, verbose_name='reader count')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('is_free', models.BooleanField(default=True, verbose_name='is free')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookRedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('max_uses', models.IntegerField(default=1, verbose_name='max uses')),
                ('used_count', models.IntegerField(default=0, verbose_name='used count')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='note')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeem_codes', to='oj_book.book')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_redeem_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'book redeem code',
                'verbose_name_plural': 'book redeem codes',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='oj_book.book')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content_type', models.CharField(choices=[('article', '文章'), ('video', '视频'), ('problem', '题目')], default='article', max_length=20, verbose_name='content type')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('video_url', models.URLField(blank=True, default='', verbose_name='video url')),
                ('estimated_time', models.IntegerField(default=5, verbose_name='estimated time')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='oj_book.chapter')),
                ('problems', models.ManyToManyField(blank=True, related_name='book_sections', to='oj_problem.Problem')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserBookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='purchased at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='oj_book.book')),
                ('redeem_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oj_book.bookredeemcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user book purchase',
                'verbose_name_plural': 'user book purchases',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='UserBookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='last read at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='oj_book.book')),
                ('completed_sections', models.ManyToManyField(blank=True, related_name='completed_by', to='oj_book.Section')),
                ('last_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='oj_book.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user book progress',
                'verbose_name_plural': 'user book progress',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
