# Generated by Django 3.2.25 on 2026-01-25 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oj_problem', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('problem_list_mode', models.BooleanField(default=False, verbose_name='problem list mode')),
                ('rule_type', models.CharField(choices=[('IOI', 'IOI (实时反馈+部分分)'), ('OI', 'OI (赛后反馈+部分分)'), ('ACM', 'ACM (实时反馈+罚时)')], default='IOI', max_length=10, verbose_name='rule type')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('freeze_time', models.DateTimeField(blank=True, help_text='封榜时间，ACM赛制使用', null=True, verbose_name='freeze time')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='hide')),
                ('allow_sign_up', models.BooleanField(default=True, verbose_name='allow sign up')),
                ('public_ranking', models.BooleanField(default=False, help_text='是否公开排行榜（未登录用户可见）', verbose_name='public ranking')),
            ],
            options={
                'verbose_name': 'contest',
                'verbose_name_plural': 'contests',
            },
        ),
        migrations.CreateModel(
            name='ContestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj_contest.contest', verbose_name='contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'contest user',
                'verbose_name_plural': 'contest users',
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj_contest.contest', verbose_name='contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='oj_problem.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'contest problem',
                'verbose_name_plural': 'contest problems',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(through='oj_contest.ContestProblem', to='oj_problem.Problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='users',
            field=models.ManyToManyField(through='oj_contest.ContestUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
