FROM node:18

WORKDIR /root

# Copy local frontend code
COPY ../frontend-naive /root/frontend

# Install dependencies
RUN cd frontend && yarn install --registry=https://registry.npmmirror.com

# Build the frontend
RUN cd frontend && yarn build

# Copy build output to mounted volume
CMD ["sh", "-c", "rm -rf /root/frontend-dist/* && cp -r /root/frontend/dist/* /root/frontend-dist/ && echo 'BUILD SUCCESS'"]
