# Generated by ChatGPT on 2026-02-15

from django.db import migrations, models
import oj_problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('oj_problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='judge_mode',
            field=models.CharField(
                choices=[('acm', 'ACM'), ('leetcode', 'LeetCode')],
                default='acm',
                max_length=20,
                verbose_name='judge mode',
            ),
        ),
        migrations.AddField(
            model_name='problem',
            name='leetcode_templates',
            field=models.JSONField(
                default=oj_problem.models.get_default_leetcode_templates,
                verbose_name='leetcode templates',
            ),
        ),
    ]
