# Generated by Django 3.2.25 on 2026-01-25 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oj_submission', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oj_problem', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('friend', 'Friend'), ('match', 'Match')], default='friend', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('difficulty_min', models.IntegerField(blank=True, null=True)),
                ('difficulty_max', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=1800)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('finish_reason', models.CharField(blank=True, choices=[('first_ac', 'First AC'), ('timeout_draw', 'Timeout Draw'), ('timeout_by_wa', 'Timeout By Wrong Attempts'), ('both_gave_up', 'Both Gave Up'), ('one_gave_up', 'One Gave Up')], max_length=30, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battle_rooms', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_rooms', to='oj_problem.problem')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battle_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'battle room',
                'verbose_name_plural': 'battle rooms',
            },
        ),
        migrations.CreateModel(
            name='BattleSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='season name')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('inherit_ratio', models.FloatField(default=0.5, help_text='继承上赛季分数的比例', verbose_name='inherit ratio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'battle season',
                'verbose_name_plural': 'battle seasons',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BattleSubmissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_submissions', to='oj_battle.battleroom')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_link', to='oj_submission.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'battle submission link',
                'verbose_name_plural': 'battle submission links',
            },
        ),
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a_rating_before', models.IntegerField(default=500)),
                ('user_a_rating_change', models.IntegerField(default=0)),
                ('user_a_exp_change', models.IntegerField(default=0)),
                ('user_a_ac_time', models.DateTimeField(blank=True, null=True, verbose_name='A AC time')),
                ('user_a_gave_up', models.BooleanField(default=False)),
                ('user_b_rating_before', models.IntegerField(default=500)),
                ('user_b_rating_change', models.IntegerField(default=0)),
                ('user_b_exp_change', models.IntegerField(default=0)),
                ('user_b_ac_time', models.DateTimeField(blank=True, null=True, verbose_name='B AC time')),
                ('user_b_gave_up', models.BooleanField(default=False)),
                ('user_a_bonus_time', models.BooleanField(default=False)),
                ('user_b_bonus_time', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='oj_battle.battleroom')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='oj_battle.battleseason')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_results_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_results_as_b', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'battle result',
                'verbose_name_plural': 'battle results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=500, verbose_name='rating')),
                ('battle_level', models.IntegerField(default=1, verbose_name='battle level')),
                ('experience', models.IntegerField(default=0, verbose_name='experience')),
                ('total_battles', models.IntegerField(default=0, verbose_name='total battles')),
                ('wins', models.IntegerField(default=0, verbose_name='wins')),
                ('losses', models.IntegerField(default=0, verbose_name='losses')),
                ('peak_rating', models.IntegerField(default=500, verbose_name='peak rating')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='oj_battle.battleseason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'battle rating',
                'verbose_name_plural': 'battle ratings',
                'ordering': ['-rating', '-peak_rating'],
                'unique_together': {('user', 'season')},
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='oj_battle.battleroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'battle participant',
                'verbose_name_plural': 'battle participants',
                'unique_together': {('room', 'side'), ('room', 'user')},
            },
        ),
    ]
